{
 "title": "New dashboard",
 "time": { "from": "2025-07-23T09:55:30.736Z", "to": "2025-07-23T10:03:34.536Z" },
 "panels": [
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (url) (rate(gin_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(gin_request_size_bytes_sum[$__rate_interval])\n",
     "legendFormat": "request"
    },
    {
     "expr": "rate(gin_response_size_bytes_sum[$__rate_interval])",
     "legendFormat": "response"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, url) (rate(gin_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}